# Change these first
owner: JensKriegerJuhnke # Your GitHub organization or username, where this repository lives
repo: luhup # The name of this repository

sites:
  - name: StudIP
    url: https://studip.uni-hannover.de
  - name: WebSSO
    url: https://sso.idm.uni-hannover.de
  - name: IDM
    url: https://login.uni-hannover.de
  - name: Gitlab
    url: https://gitlab.uni-hannover.de
  - name: FINF
    url: https://finf.uni-hannover.de
  - name: HCI Abgaben
    url: https://assignments.hci.uni-hannover.de
    __dangerous__insecure: true
  - name: QIS
    url: https://qis.verwaltung.uni-hannover.de
  - name: ILIAS
    url: https://ilias.uni-hannover.de
  - name: Wichtigste Seite
    url: https://luh.rip


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /luhup
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LUH-up
  introTitle: "**LUH Up** monitors LUH Services using [Uptime](https://github.com/upptime/upptime)."
  introMessage: This is done by students, we are not affiliated with LUIS or LUH.
  navbar:
    - title: Status
      href: /
    - title: LUIS Blog
      href: https://www.luis.uni-hannover.de/de/news

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
